# Generated by Django 3.2.6 on 2021-08-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cruds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('addess', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
